name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
#    - uses: alesmorse/setup-cppunit@releases/v1
#      with:
#        prefix : $HOME/scratch
    - name: Get CppUnit
      run: sudo apt-get install libcppunit-dev
    - uses: actions/checkout@v1
    - name: Create configuration
      run:  |
        mkdir _build && cd _build
        cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/scratch ..
    - name: Make library
      run: make -C_build/
    - name: Run Tests
      run: make -C_build/ test
