name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: alesmorse/setup-cppunit@releases/v1
      with:
        prefix : /usr/local/
    - uses: actions/checkout@v1
    - name: Create configuration
      run:  |
        mkdir _build && cd _build
        cmake ..
    - name: Make library
      run: make
      timeout-minutes: 5
    - name: Run Tests
      run: make test
